<?php

/**
 * @file
 * Drupal Pilipinas core module.
 */


/**
 * Implements hook_block_info().
 */
function drupinas_core_block_info() {
  $blocks = array();
 
  $blocks['copyright'] = array(
    'info' => t('Copyright'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['aboutfooter'] = array(
    'info' => t('About Footer'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['login'] = array(
    'info' =>  t('Login'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );

  return $blocks;
}


/**
 * Implements hook_block_info_alter().
 */
function drupinas_core_block_info_alter(&$blocks, $theme, $code_blocks) {
  $blocks['user']['login']['status'] = 0;
  $blocks['search']['form']['status'] = 0;
  $blocks['system']['navigation']['status'] = 0;
}


/**
 * Implements hook_block_view().
 */
function drupinas_core_block_view($delta = '') {
  $blocks = array();

  switch ($delta) {
    case 'aboutfooter':
      $blocks['content'] = _load_about_us();
      $blocks['subject'] = '';
      break;

    case 'copyright':
      $blocks['content'] = '';
      $blocks['subject'] = t('Copyright');
      break;

    case 'login':
      $blocks['content'] = _user_login();
			$blocks['subject'] = t('Login');

    default:
      break;
  }
  return $blocks;
}


/**
 *  Helper function.
 */
function _user_login() {
  $html = '';
  if (user_is_anonymous()) {
    $html = l(t('Sign In'), "user");
  }
  return $html;
}


/**
 * About Footer helper function.
 */
function _load_about_us() {
  $about_node = node_load(22);
	$about_view = node_view($about_node, 'teaser');
  //print_r($about_view);
	$about = drupal_render($about_view);

  return $about;
} 
